services:
  - type: web
    name: spam-mail-detector
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m src.train_model
    startCommand: gunicorn app.app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CREDENTIALS_PATH
        value: /etc/secrets/credentials.json